# Generated by Django 3.2.22 on 2024-06-17 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_acessosrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessosrecord',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
