# Generated by Django 3.2.22 on 2024-06-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_alter_acessosrecord_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264, unique=True)),
                ('last_name', models.CharField(max_length=264, unique=True)),
                ('email', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
