# Generated by Django 3.2.22 on 2024-06-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='WebsiteUser',
        ),
    ]
